/**
 * Convex API Configuration
 *
 * IMPORTANT: This file is auto-generated by `npx convex codegen` when connected
 * to a live Convex cloud deployment. Until NEXT_PUBLIC_CONVEX_URL is set to a
 * real convex.cloud URL, the app runs in STATIC_MODE using local data fallbacks.
 *
 * TO ACTIVATE LIVE CONVEX:
 * 1. Log in: npx convex login
 * 2. Deploy: npx convex deploy
 * 3. Copy NEXT_PUBLIC_CONVEX_URL from .env.local to Vercel environment variables
 * 4. Redeploy on Vercel
 */

const functionNameSymbol = Symbol.for("functionName");

const makeProxy = (path: string[] = []): any => {
  return new Proxy(
    {
      _path: path.join(":"),
      _type: "query",
      toString() {
        return path.join(":");
      }
    },
    {
      get(target: any, prop: string | symbol) {
        if (prop === functionNameSymbol) {
          if (path.length < 2) {
            return path.join(":");
          }
          const dirPath = path.slice(0, -1).join("/");
          const exportName = path[path.length - 1];
          return dirPath + ":" + exportName;
        }
        if (typeof prop === "symbol" || prop === "then" || prop === "toJSON") {
          return undefined;
        }
        if (prop === "_path" || prop === "_type" || prop === "toString") {
          return target[prop];
        }
        return makeProxy([...path, String(prop)]);
      }
    }
  );
};

export const api = makeProxy([]);
export const internal = makeProxy([]);

// Check if we have a real cloud URL
export const IS_CONVEX_LIVE =
  typeof process !== 'undefined' &&
  process.env.NEXT_PUBLIC_CONVEX_URL?.includes('convex.cloud');
