'use client';

import React from 'react';
import Link from 'next/link';
import { 
  Cloud, FileSpreadsheet, FileText, Presentation, Database, 
  ExternalLink, Share2, ArrowLeft, Shield, Cpu, BookOpen, AlertCircle
} from 'lucide-react';

export default function SovereignWorkspace() {
  const notebooks = [
    {
      id: 'epd-notebook',
      title: 'Guurti Sovereign Peacemaking & EPD Intelligence',
      url: 'https://notebooklm.google.com/notebook/2b5a027a-51ca-4f99-971a-f6dace367aa9',
      sources: 14,
      status: 'SYNCED',
      description: 'NotebookLM instance loaded with the Somaliland Constitution, IPU guides, traditional Ogo conference peace agreements, and external partner frameworks.'
    }
  ];

  return (
    <div className="min-h-screen bg-[#050507] text-[#F0EEE8] font-sans selection:bg-[#008A51]/30">
      
      {/* Header */}
      <header className="sticky top-0 z-20 border-b border-[#008A51]/30 bg-[#050507]/90 backdrop-blur-xl px-8 py-4 flex justify-between items-center">
        <div className="flex items-center gap-4">
          <Link href="/epd" className="p-2 hover:bg-white/5 rounded-xl transition-all">
            <ArrowLeft className="w-5 h-5 text-zinc-400 hover:text-white" />
          </Link>
          <div className="h-6 w-[1px] bg-white/10" />
          <div>
            <h1 className="text-xl font-bold tracking-widest text-white uppercase flex items-center gap-2">
              Sovereign Workspace <span className="text-[#D4AF37]">•</span> Document Intelligence
            </h1>
            <p className="text-[#008A51] text-xs tracking-wider uppercase">Google Ecosystem & NotebookLM Integration Gateway</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-full border border-[#008A51]/20 bg-[#008A51]/5 text-xs text-[#008A51] font-semibold">
          <Cloud className="w-3.5 h-3.5 animate-pulse" />
          Google Cloud Connected
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-8 space-y-12">

        {/* Top Info Alert */}
        <section className="bg-gradient-to-r from-[#008A51]/10 to-[#D4AF37]/5 border border-[#008A51]/20 rounded-2xl p-6 flex items-start gap-4">
          <Shield className="w-6 h-6 text-[#D4AF37] shrink-0 mt-0.5" />
          <div className="space-y-2">
            <h3 className="text-md font-bold text-white">Google One & Sovereign Cloud Integration</h3>
            <p className="text-sm text-zinc-400 max-w-4xl">
              This intelligence workspace bridges Somaliland's indigenous legislative memory with Google Cloud and NotebookLM. 
              All drafted Concept Notes, Expressions of Interest (EOIs), and bilateral MoUs generated by the EPD platform are securely synced to your Google Workspace for collaborative drafting and presentation.
            </p>
          </div>
        </section>

        {/* Google Workspace Grid */}
        <section className="grid grid-cols-1 md:grid-cols-4 gap-6">
          
          {/* Google Drive */}
          <div className="p-6 bg-[#0A0A0F]/80 border border-[#008A51]/10 rounded-2xl hover:border-[#008A51]/30 hover:shadow-lg hover:shadow-[#008A51]/5 transition-all flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-400 mb-4 group-hover:scale-105 transition-transform">
                <Database className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">EPD Master Archive</h3>
              <p className="text-xs text-zinc-400 leading-relaxed mb-4">
                Secure repository on Google Drive holding historical correspondence, official credentials, and committee agendas.
              </p>
            </div>
            <button className="w-full py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold text-zinc-300 hover:text-white transition-all flex items-center justify-center gap-2">
              Access Drive <ExternalLink className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Google Sheets */}
          <div className="p-6 bg-[#0A0A0F]/80 border border-[#008A51]/10 rounded-2xl hover:border-[#008A51]/30 hover:shadow-lg hover:shadow-[#008A51]/5 transition-all flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 mb-4 group-hover:scale-105 transition-transform">
                <FileSpreadsheet className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">Funding Pipeline Sheets</h3>
              <p className="text-xs text-zinc-400 leading-relaxed mb-4">
                Active tracking sheet detailing $242M+ in strategic opportunities, donor procurement cycles, and submission windows.
              </p>
            </div>
            <button className="w-full py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold text-zinc-300 hover:text-white transition-all flex items-center justify-center gap-2">
              Launch Sheet <ExternalLink className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Google Docs */}
          <div className="p-6 bg-[#0A0A0F]/80 border border-[#008A51]/10 rounded-2xl hover:border-[#008A51]/30 hover:shadow-lg hover:shadow-[#008A51]/5 transition-all flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-400 mb-4 group-hover:scale-105 transition-transform">
                <FileText className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">Sovereign Proposal Docs</h3>
              <p className="text-xs text-zinc-400 leading-relaxed mb-4">
                Export target drafts directly to collaborative Google Doc files using parliamentary templates with correct metadata blocks.
              </p>
            </div>
            <button className="w-full py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold text-zinc-300 hover:text-white transition-all flex items-center justify-center gap-2">
              Open Templates <ExternalLink className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Google Slides */}
          <div className="p-6 bg-[#0A0A0F]/80 border border-[#008A51]/10 rounded-2xl hover:border-[#008A51]/30 hover:shadow-lg hover:shadow-[#008A51]/5 transition-all flex flex-col justify-between group">
            <div>
              <div className="w-12 h-12 rounded-xl bg-orange-500/10 flex items-center justify-center text-orange-400 mb-4 group-hover:scale-105 transition-transform">
                <Presentation className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">Diplomatic Slides</h3>
              <p className="text-xs text-zinc-400 leading-relaxed mb-4">
                Guurti bilateral and strategic presentations for international delegates, IPU seminars, and donor alignment pitches.
              </p>
            </div>
            <button className="w-full py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold text-zinc-300 hover:text-white transition-all flex items-center justify-center gap-2">
              Open Slides <ExternalLink className="w-3.5 h-3.5" />
            </button>
          </div>

        </section>

        {/* NotebookLM Integrated Hub Section */}
        <section className="bg-gradient-to-br from-[#0A0A12] to-[#0A0A05] border border-[#D4AF37]/20 rounded-3xl p-8 relative overflow-hidden">
          <div className="absolute top-0 right-0 -m-16 w-72 h-72 bg-[#D4AF37]/5 blur-[120px] rounded-full" />
          <div className="absolute bottom-0 left-0 -m-16 w-60 h-60 bg-[#008A51]/5 blur-[100px] rounded-full" />

          <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            
            <div className="lg:col-span-8 space-y-6">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#D4AF37]/10 border border-[#D4AF37]/20 text-[#D4AF37] text-xs font-bold tracking-wider uppercase">
                <Cpu size={12} fill="currentColor" />
                NotebookLM Active Bridge
              </div>
              <h2 className="text-3xl lg:text-4xl font-extrabold text-white leading-tight">
                Sovereign Knowledge Engine
              </h2>
              <p className="text-zinc-400 text-md leading-relaxed">
                Connect your EPD workflows directly to your specialized Google NotebookLM system. 
                Using the bridged workspace, your customized AI model analyzes institutional documents, constitutional articles, and traditional peace-building records to generate contextually perfect policies.
              </p>
              
              <div className="p-4 bg-black/40 border border-zinc-800 rounded-xl flex items-center gap-3 max-w-xl text-xs text-zinc-400">
                <AlertCircle className="w-5 h-5 text-[#D4AF37] shrink-0" />
                <span>Make sure you are logged into your primary Google Account on this browser to access your private notebook directly.</span>
              </div>
            </div>

            <div className="lg:col-span-4 flex justify-end">
              <div className="p-6 bg-[#0A0A0A]/90 border border-[#D4AF37]/30 rounded-2xl shadow-2xl w-full max-w-sm space-y-6">
                <div>
                  <h4 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-1">Target Instance</h4>
                  <h3 className="text-lg font-bold text-white mb-2">Notebook 2B5A027A</h3>
                  <p className="text-[11px] text-zinc-400 leading-relaxed">
                    Access your specific, fully loaded research notebook: <code className="bg-white/5 px-1 py-0.5 rounded text-white font-mono">2b5a027a-...</code>.
                  </p>
                </div>
                <div className="h-[1px] bg-zinc-800" />
                <div className="space-y-2">
                  <a 
                    href="https://notebooklm.google.com/notebook/2b5a027a-51ca-4f99-971a-f6dace367aa9" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="w-full py-3 bg-[#D4AF37] hover:bg-[#AA8B2E] text-black font-extrabold rounded-xl transition-all shadow-xl shadow-[#D4AF37]/10 flex items-center justify-center gap-2 text-sm"
                  >
                    Open NotebookLM <ArrowLeft className="w-4 h-4 rotate-180" />
                  </a>
                </div>
              </div>
            </div>

          </div>
        </section>

        {/* Documents Ingestion List */}
        <section className="space-y-6">
          <div>
            <h2 className="text-xl font-bold uppercase tracking-wider text-white">Sovereign Source Documents (NotebookLM Sync)</h2>
            <p className="text-zinc-500 text-xs mt-1">Cross-referenced legal and traditional resources mapped in your Google Workspace library.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            <div className="p-5 bg-[#0A0A0F]/80 border border-zinc-800 rounded-2xl flex gap-4">
              <div className="w-10 h-10 rounded-lg bg-zinc-800 flex items-center justify-center text-[#D4AF37]">
                <FileText size={20} />
              </div>
              <div>
                <h4 className="text-sm font-semibold text-white">Constitution of Somaliland</h4>
                <p className="text-[11px] text-zinc-500 mt-1">Articles 12 & 61 mapping parameters for compliance auditing.</p>
              </div>
            </div>

            <div className="p-5 bg-[#0A0A0F]/80 border border-zinc-800 rounded-2xl flex gap-4">
              <div className="w-10 h-10 rounded-lg bg-zinc-800 flex items-center justify-center text-emerald-400">
                <BookOpen size={20} />
              </div>
              <div>
                <h4 className="text-sm font-semibold text-white">The Ogo Peace Treaties</h4>
                <p className="text-[11px] text-zinc-500 mt-1">Indigenous reconciliation records utilized for peace building KPIs.</p>
              </div>
            </div>

            <div className="p-5 bg-[#0A0A0F]/80 border border-zinc-800 rounded-2xl flex gap-4">
              <div className="w-10 h-10 rounded-lg bg-zinc-800 flex items-center justify-center text-blue-400">
                <Share2 size={20} />
              </div>
              <div>
                <h4 className="text-sm font-semibold text-white">IPU Governance Standards</h4>
                <p className="text-[11px] text-zinc-500 mt-1">Parliamentary metrics guidelines used for ex-ante scoring.</p>
              </div>
            </div>

          </div>
        </section>

      </main>

    </div>
  );
}
